# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CRUD-Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVC-Swift
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftValidator', :git => 'https://github.com/jpotts18/SwiftValidator.git', :tag => '4.2.0'
  pod 'DropDown'
  pod 'JJFloatingActionButton'
  pod 'SwiftyJSON'
  pod 'SVProgressHUD'
  pod 'Toast-Swift', '~> 5.0.1'
end
